language: ruby
cache: bundler
before_script: createdb -U postgres attr_vault
dist: trusty
sudo: false
script: DATABASE_URL="postgres:///attr_vault" bundle exec rspec
addons:
  postgresql: "9.6"
notifications:
  email: false
